// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Avoid a hard crash during module initialization when env vars are missing.
// In that scenario the app runs in "degraded mode" (chat/auth will fail until configured).
const SAFE_SUPABASE_URL = SUPABASE_URL || "http://localhost:54321";
const SAFE_SUPABASE_PUBLISHABLE_KEY = SUPABASE_PUBLISHABLE_KEY || "invalid";

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    "[Supabase] Missing VITE_SUPABASE_URL/VITE_SUPABASE_PUBLISHABLE_KEY. Configure them in your hosting environment."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SAFE_SUPABASE_URL, SAFE_SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
